name: Build Check

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main, develop]

jobs:
  build_check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: grant permission
        run: chmod +x gradlew

      - name: build check
        shell: bash
        run: |
          ./gradlew assembleDebug
        
