name: Build Check

on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main, develop ]

jobs:
  build_check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: grant permission
        run: chmod +x gradlew

      - name: create local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        shell: bash
        run: |
          echo "${LOCAL_PROPERTIES}" > ./local.properties

      - name: build check
        shell: bash
        run: |
          ./gradlew assembleDebug
        
